### ISSUE TITLE
貌似对Monterey 12.3的支持不是很好

### ISSUE THREAD

**Issue by pengyuan560** [daliansky/TinyMonsterMix-Hackintosh#1]
升级到Monterey 12.3之后出现部分图标花了的现象，部分自带应用也有花屏现象，第三方应用未出现花屏。降级两次后升级都是出现同样的现象。

**Comment by vt-rli** [comment]
> 升级到Monterey 12.3之后出现部分图标花了的现象，部分自带应用也有花屏现象，第三方应用未出现花屏。降级两次后升级都是出现同样的现象。

需升级显卡驱动
https://github.com/osy/Polaris22Fixup/releases
